/* THIS IS AN AUTOGENERATED/BUNDLED FILE BY ESBUILD */
if (typeof window !== 'undefined' && window.require) { window.require = undefined; window.module = undefined; }
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MoveToNewFolderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultToCurrentParent: true
};
var ParentFolderPickerModal = class extends import_obsidian.Modal {
  constructor(app, initialPath, onCloseResolve) {
    super(app);
    this.searchValue = "";
    this.selectedIndex = 0;
    this.listByPath = /* @__PURE__ */ new Map();
    this.didResolve = false;
    this.initialPath = initialPath;
    this.selectedPath = initialPath;
    this.onCloseResolve = onCloseResolve;
    this.folderPaths = this.collectFolderPaths();
    if (!this.folderPaths.includes(this.selectedPath)) {
      this.selectedPath = "";
    }
  }
  onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("move-to-new-folder-modal");
    contentEl.empty();
    contentEl.createEl("h2", { text: "Choose a parent folder" });
    contentEl.createEl("p", {
      text: "Search by typing or pick a folder from the list.",
      cls: "move-to-new-folder-hint"
    });
    const searchInput = contentEl.createEl("input", {
      type: "text",
      placeholder: "Search folders...",
      cls: "move-to-new-folder-search"
    });
    const listEl = contentEl.createDiv({ cls: "move-to-new-folder-list" });
    const render = () => {
      listEl.empty();
      this.listByPath.clear();
      const filtered = this.getFilteredFolders();
      if (filtered.length === 0) {
        listEl.createDiv({
          text: "No folders match your search.",
          cls: "move-to-new-folder-empty"
        });
        return;
      }
      if (this.selectedIndex >= filtered.length) {
        this.selectedIndex = 0;
      }
      const selectedByIndex = filtered[this.selectedIndex];
      this.selectedPath = selectedByIndex;
      for (const folderPath of filtered) {
        const button = listEl.createEl("button", {
          cls: "move-to-new-folder-item",
          text: folderPath.length > 0 ? folderPath : "/"
        });
        button.type = "button";
        button.dataset.path = folderPath;
        if (folderPath === this.selectedPath) {
          button.addClass("is-selected");
        }
        button.addEventListener("click", () => {
          this.selectedPath = folderPath;
          this.closeWithResult(folderPath);
        });
        button.addEventListener("mouseenter", () => {
          const idx = filtered.indexOf(folderPath);
          if (idx >= 0) {
            this.selectedIndex = idx;
            this.selectedPath = folderPath;
            this.refreshSelection(listEl, filtered);
          }
        });
        this.listByPath.set(folderPath, button);
      }
      this.refreshSelection(listEl, filtered);
    };
    searchInput.addEventListener("input", () => {
      this.searchValue = searchInput.value.trim();
      this.selectedIndex = 0;
      render();
    });
    searchInput.addEventListener("keydown", (event) => {
      const filtered = this.getFilteredFolders();
      if (event.key === "ArrowDown") {
        event.preventDefault();
        if (filtered.length > 0) {
          this.selectedIndex = Math.min(this.selectedIndex + 1, filtered.length - 1);
          this.selectedPath = filtered[this.selectedIndex];
          this.refreshSelection(listEl, filtered);
        }
      }
      if (event.key === "ArrowUp") {
        event.preventDefault();
        if (filtered.length > 0) {
          this.selectedIndex = Math.max(this.selectedIndex - 1, 0);
          this.selectedPath = filtered[this.selectedIndex];
          this.refreshSelection(listEl, filtered);
        }
      }
      if (event.key === "Enter") {
        event.preventDefault();
        if (filtered.length > 0) {
          this.closeWithResult(filtered[this.selectedIndex]);
        }
      }
    });
    const actionsEl = contentEl.createDiv({ cls: "move-to-new-folder-actions" });
    const cancelButton = actionsEl.createEl("button", {
      text: "Cancel",
      cls: "mod-muted"
    });
    cancelButton.type = "button";
    cancelButton.addEventListener("click", () => this.closeWithResult(null));
    const chooseButton = actionsEl.createEl("button", {
      text: "Choose",
      cls: "mod-cta"
    });
    chooseButton.type = "button";
    chooseButton.addEventListener("click", () => this.closeWithResult(this.selectedPath));
    render();
    searchInput.focus();
    searchInput.select();
  }
  onClose() {
    if (!this.didResolve) {
      this.onCloseResolve({ selectedPath: null });
    }
    this.modalEl.removeClass("move-to-new-folder-modal");
    this.contentEl.empty();
  }
  collectFolderPaths() {
    const folderSet = /* @__PURE__ */ new Set([""]);
    for (const item of this.app.vault.getAllLoadedFiles()) {
      if (item instanceof import_obsidian.TFolder) {
        folderSet.add(item.path);
      }
    }
    return Array.from(folderSet).sort((a, b) => a.localeCompare(b));
  }
  getFilteredFolders() {
    if (!this.searchValue) {
      return this.folderPaths;
    }
    const needle = this.searchValue.toLocaleLowerCase();
    return this.folderPaths.filter((path) => {
      const haystack = path.length > 0 ? path.toLocaleLowerCase() : "/";
      return haystack.includes(needle);
    });
  }
  refreshSelection(listEl, filtered) {
    for (const [path, button] of this.listByPath.entries()) {
      const shouldSelect = path === this.selectedPath;
      button.toggleClass("is-selected", shouldSelect);
      if (shouldSelect) {
        button.scrollIntoView({ block: "nearest" });
      }
    }
    if (!filtered.includes(this.selectedPath) && filtered.length > 0) {
      this.selectedIndex = 0;
      this.selectedPath = filtered[0];
      this.refreshSelection(listEl, filtered);
    }
  }
  closeWithResult(selectedPath) {
    this.didResolve = true;
    this.onCloseResolve({ selectedPath });
    this.close();
  }
};
var TextPromptModal = class extends import_obsidian.Modal {
  constructor(app, title, placeholder, submitText, onCloseResolve) {
    super(app);
    this.didResolve = false;
    this.title = title;
    this.placeholder = placeholder;
    this.submitText = submitText;
    this.onCloseResolve = onCloseResolve;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    const input = contentEl.createEl("input", {
      type: "text",
      placeholder: this.placeholder
    });
    const hintEl = contentEl.createDiv({
      text: "Enter only a folder name, not a full path.",
      cls: "move-to-new-folder-hint"
    });
    const actionsEl = contentEl.createDiv({ cls: "move-to-new-folder-actions" });
    const cancelButton = actionsEl.createEl("button", {
      text: "Cancel",
      cls: "mod-muted"
    });
    cancelButton.type = "button";
    cancelButton.addEventListener("click", () => this.closeWithResult(null));
    const submitButton = actionsEl.createEl("button", {
      text: this.submitText,
      cls: "mod-cta"
    });
    submitButton.type = "button";
    const submit = () => {
      const value = input.value.trim();
      if (!value) {
        new import_obsidian.Notice("Folder name cannot be empty.");
        return;
      }
      if (value.includes("/") || value.includes("\\")) {
        hintEl.setText("Folder name cannot contain path separators.");
        return;
      }
      this.closeWithResult(value);
    };
    submitButton.addEventListener("click", submit);
    input.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        submit();
      }
    });
    input.focus();
    input.select();
  }
  onClose() {
    if (!this.didResolve) {
      this.onCloseResolve({ value: null });
    }
    this.contentEl.empty();
  }
  closeWithResult(value) {
    this.didResolve = true;
    this.onCloseResolve({ value });
    this.close();
  }
};
var ConfirmationModal = class extends import_obsidian.Modal {
  constructor(app, titleText, bodyText, confirmText, onCloseResolve) {
    super(app);
    this.didResolve = false;
    this.titleText = titleText;
    this.bodyText = bodyText;
    this.confirmText = confirmText;
    this.onCloseResolve = onCloseResolve;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.titleText });
    contentEl.createEl("p", { text: this.bodyText });
    const actionsEl = contentEl.createDiv({ cls: "move-to-new-folder-actions" });
    const cancelButton = actionsEl.createEl("button", {
      text: "Cancel",
      cls: "mod-muted"
    });
    cancelButton.type = "button";
    cancelButton.addEventListener("click", () => this.closeWithResult(false));
    const confirmButton = actionsEl.createEl("button", {
      text: this.confirmText,
      cls: "mod-cta"
    });
    confirmButton.type = "button";
    confirmButton.addEventListener("click", () => this.closeWithResult(true));
  }
  onClose() {
    if (!this.didResolve) {
      this.onCloseResolve(false);
    }
    this.contentEl.empty();
  }
  closeWithResult(confirmed) {
    this.didResolve = true;
    this.onCloseResolve(confirmed);
    this.close();
  }
};
var MoveToNewFolderSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Move to New Folder settings" });
    new import_obsidian.Setting(containerEl).setName("Default parent to current note folder").setDesc("When enabled, the folder picker starts at the current note's parent folder.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.defaultToCurrentParent).onChange(async (value) => {
        this.plugin.settings.defaultToCurrentParent = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
var MoveToNewFolderPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MoveToNewFolderSettingTab(this.app, this));
    this.addCommand({
      id: "move-note-to-new-folder",
      name: "Move note to new folder",
      checkCallback: (checking) => {
        const context = this.getActiveMarkdownFileContext();
        if (!context) {
          return false;
        }
        if (!checking) {
          void this.runMoveFlow(context.file, context.leaf);
        }
        return true;
      }
    });
    this.app.workspace.onLayoutReady(() => {
      this.registerFileMenuAction();
    });
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  registerFileMenuAction() {
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file, _source, leaf) => {
        if (!this.isMarkdownFile(file)) {
          return;
        }
        menu.addItem((item) => {
          item.setTitle("Move note to new folder").setIcon("folder-plus").onClick(() => {
            void this.runMoveFlow(file, leaf);
          });
        });
      })
    );
  }
  async runMoveFlow(file, leaf) {
    var _a, _b;
    const parentDefaultPath = this.settings.defaultToCurrentParent ? (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "" : "";
    const pickedParent = await this.pickParentFolder(parentDefaultPath);
    if (pickedParent === null) {
      return;
    }
    const newFolderName = await this.promptForFolderName();
    if (newFolderName === null) {
      return;
    }
    const targetFolderPath = (0, import_obsidian.normalizePath)(
      pickedParent.length > 0 ? `${pickedParent}/${newFolderName}` : newFolderName
    );
    const targetFolder = await this.ensureTargetFolder(targetFolderPath);
    if (!targetFolder) {
      return;
    }
    const targetFilePath = (0, import_obsidian.normalizePath)(`${targetFolder.path}/${file.name}`);
    const existingDestination = this.app.vault.getAbstractFileByPath(targetFilePath);
    if (existingDestination && existingDestination.path !== file.path) {
      new import_obsidian.Notice(`Move canceled: file already exists at "${targetFilePath}".`);
      return;
    }
    try {
      await this.app.fileManager.renameFile(file, targetFilePath);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      new import_obsidian.Notice(`Could not move note: ${message}`);
      return;
    }
    const movedFile = this.app.vault.getAbstractFileByPath(targetFilePath);
    if (movedFile instanceof import_obsidian.TFile) {
      await this.openMovedFile(movedFile, leaf);
      new import_obsidian.Notice(`Moved to "${targetFolderPath}".`);
      return;
    }
    new import_obsidian.Notice(`Move completed, but could not reopen "${targetFilePath}".`);
  }
  async ensureTargetFolder(targetFolderPath) {
    const existing = this.app.vault.getAbstractFileByPath(targetFolderPath);
    if (existing instanceof import_obsidian.TFolder) {
      const confirmed = await this.confirmReuseFolder(targetFolderPath);
      if (!confirmed) {
        return null;
      }
      return existing;
    }
    if (existing) {
      new import_obsidian.Notice(`Cannot use "${targetFolderPath}": a file already exists at that path.`);
      return null;
    }
    try {
      await this.app.vault.createFolder(targetFolderPath);
    } catch (error) {
      const raceWinner = this.app.vault.getAbstractFileByPath(targetFolderPath);
      if (raceWinner instanceof import_obsidian.TFolder) {
        return raceWinner;
      }
      const message = error instanceof Error ? error.message : String(error);
      new import_obsidian.Notice(`Could not create folder: ${message}`);
      return null;
    }
    const created = this.app.vault.getAbstractFileByPath(targetFolderPath);
    if (created instanceof import_obsidian.TFolder) {
      return created;
    }
    new import_obsidian.Notice(`Folder creation succeeded but "${targetFolderPath}" is unavailable.`);
    return null;
  }
  async confirmReuseFolder(folderPath) {
    return new Promise((resolve) => {
      const modal = new ConfirmationModal(
        this.app,
        "Folder already exists",
        `Use existing folder "${folderPath}"?`,
        "Use folder",
        resolve
      );
      modal.open();
    });
  }
  async pickParentFolder(initialPath) {
    return new Promise((resolve) => {
      const modal = new ParentFolderPickerModal(this.app, initialPath, (result) => {
        resolve(result.selectedPath);
      });
      modal.open();
    });
  }
  async promptForFolderName() {
    return new Promise((resolve) => {
      const modal = new TextPromptModal(
        this.app,
        "Create a new folder",
        "New folder name",
        "Continue",
        (result) => {
          resolve(result.value);
        }
      );
      modal.open();
    });
  }
  async openMovedFile(file, leaf) {
    const targetLeaf = leaf != null ? leaf : this.app.workspace.getMostRecentLeaf();
    if (!targetLeaf) {
      return;
    }
    await targetLeaf.openFile(file, { active: true });
  }
  getActiveMarkdownFileContext() {
    var _a;
    const file = this.app.workspace.getActiveFile();
    if (!file || file.extension !== "md") {
      return null;
    }
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    const leaf = (_a = markdownView == null ? void 0 : markdownView.leaf) != null ? _a : this.app.workspace.getMostRecentLeaf();
    return { file, leaf: leaf != null ? leaf : void 0 };
  }
  isMarkdownFile(file) {
    return file instanceof import_obsidian.TFile && file.extension === "md";
  }
};
